---
version: "3"

services:
  webapp:
    image: fbm95/voting_img
    ports:
      - 1221:1221
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

# docker run -d --name results -p 1221:1221 voting_img
